const asset = (name: string) => `${import.meta.env.BASE_URL}assets/${name}`;

export type Service = {
  id: string; slug: string; name: string; category: string; shortDescription: string;
  description: string; headline: string; subheadline: string; primaryCTA: string;
  whatsappMessage: string; keywords: string[]; seoTitle: string; metaDescription: string;
  benefits: string[]; process: string[]; requirements: string[]; faq: { q: string; a: string }[];
  relatedServices: string[]; image: string; featured?: boolean; tier: 1 | 2 | 3;
};

export const siteData = {
  company: { name: 'مكتب ريان للمساحة والاستشارات الهندسية', shortName: 'مكتب ريان', tagline: 'خبرة هندسية موثوقة' },
  contact: { phone: '+966503130302', displayPhone: '+966 50 313 0302', email: 'info@ryan-sa.com', city: 'الرياض، المملكة العربية السعودية', hours: 'السبت – الخميس | 8:00 صباحًا حتى 5:00 مساءً', whatsapp: 'https://wa.me/966503130302' },
  stats: [{ value: '+7', label: 'سنوات خبرة' }, { value: '+300', label: 'مشروع هندسي ناجح' }, { value: '+1000', label: 'عميل وشريك نجاح' }, { value: '100%', label: 'التزام بمعايير الكود السعودي' }],
  heroImages: [asset('hero-1_db27bcc7.jpg'),asset('hero-2_8b39134c.jpg'),asset('hero-3_a0794151.jpg')],
  services: [
    { id:'surveying', slug:'surveying', name:'رفع مساحي', category:'الأعمال المساحية', shortDescription:'قياس ورصد حدود العقار أو الأرض ونقلها بدقة إلى خرائط هندسية.', description:'عملية قياس ورصد حدود العقار أو الأرض على الواقع ونقلها بدقة إلى خرائط هندسية باستخدام أجهزة مساحية متخصصة.', headline:'رفع مساحي دقيق لاتخاذ قرار واثق', subheadline:'نحوّل واقع الأرض إلى بيانات هندسية واضحة تساعدك على البدء بالشكل الصحيح.', primaryCTA:'اطلب رفعاً مساحياً', whatsappMessage:'مرحباً، أرغب في طلب خدمة الرفع المساحي.', keywords:['رفع مساحي بالرياض','مكتب رفع مساحي','رفع مساحي للأراضي','توقيع مساحي','حدود الأرض','المناسيب'], seoTitle:'رفع مساحي بالرياض | مكتب ريان للمساحة', metaDescription:'اطلب خدمة رفع مساحي دقيقة للأراضي والعقارات من مكتب ريان للمساحة والاستشارات الهندسية.', benefits:['تحديد واضح لحدود العقار','بيانات دقيقة للمناسيب والأبعاد','خرائط هندسية تساعد على التصميم والتنفيذ'], process:['فهم موقع المشروع واحتياجه','تنفيذ أعمال القياس والرصد','إعداد وتسليم المخرجات الهندسية'], requirements:['بيانات العقار المتوفرة','موقع المشروع','أي مخططات أو مستندات ذات صلة'], faq:[{q:'ما المقصود بالرفع المساحي؟',a:'هو قياس وتوثيق أبعاد وحدود ومناسيب الموقع على الواقع وتحويلها إلى مخططات هندسية.'},{q:'متى أحتاج إلى رفع مساحي؟',a:'عند بدء تصميم أو تطوير أرض أو عقار، أو عند الحاجة إلى معرفة الحدود والمناسيب بدقة.'}], relatedServices:['declaration','architectural-design'], image:'https://ryan-sa.com/wp-content/uploads/2026/06/Artboard-21-300x210.webp', featured:true, tier:1 },
    { id:'building-permit', slug:'building-permit', name:'إصدار رخصة بناء', category:'الرخص والاعتمادات', shortDescription:'استخراج رخص البناء الجديدة عبر منصة بلدي بوضوح واعتمادية.', description:'خدمة مساعدة في تجهيز متطلبات إصدار رخصة البناء ومتابعة الطلب وفق نطاق المشروع ومتطلباته.', headline:'ابدأ مشروعك برخصة بناء واضحة', subheadline:'نساعدك على فهم المتطلبات وتجهيز مسار الطلب بشكل منظم.', primaryCTA:'ابدأ طلب رخصة البناء', whatsappMessage:'مرحباً، أرغب في بدء طلب رخصة بناء.', keywords:['إصدار رخصة بناء','رخصة بناء بالرياض','رخص البناء','منصة بلدي'], seoTitle:'إصدار رخصة بناء بالرياض | مكتب ريان', metaDescription:'ابدأ طلب إصدار رخصة بناء مع مكتب ريان للمساحة والاستشارات الهندسية.', benefits:['فهم متطلبات الطلب','تنظيم المستندات والبيانات','متابعة مسار الإجراء بوضوح'], process:['مراجعة بيانات المشروع','تحديد المتطلبات المناسبة','تجهيز ومتابعة الطلب'], requirements:['بيانات المالك','مستندات العقار المتوفرة','معلومات المشروع'], faq:[{q:'ما المتطلبات اللازمة للرخصة؟',a:'تختلف المتطلبات حسب نوع المشروع وموقعه، ويتم تحديدها بعد مراجعة بيانات المشروع.'}], relatedServices:['surveying','architectural-design'], image:'https://ryan-sa.com/wp-content/uploads/2026/06/Artboard-6-300x210.webp', featured:true, tier:1 },
    { id:'deed-update', slug:'deed-update', name:'تحديث الصكوك', category:'الخدمات العقارية', shortDescription:'تحويل الصكوك العقارية الورقية القديمة إلى صكوك إلكترونية موثقة.', description:'مساعدة هندسية في تجهيز بيانات العقار والمستندات اللازمة لمسار تحديث الصكوك العقارية.', headline:'حدّث صكك ببيانات أوضح', subheadline:'نرتب لك المعلومات الهندسية اللازمة قبل تقديم طلب التحديث.', primaryCTA:'اطلب تحديث الصك', whatsappMessage:'مرحباً، أرغب في طلب خدمة تحديث الصكوك.', keywords:['تحديث الصكوك','صك إلكتروني','تحديث صك عقاري'], seoTitle:'تحديث الصكوك العقارية | مكتب ريان', metaDescription:'خدمة تحديث الصكوك العقارية وتجهيز البيانات اللازمة من مكتب ريان.', benefits:['مراجعة بيانات العقار','تجهيز المعلومات الهندسية','وضوح الخطوة التالية'], process:['مراجعة الصك والبيانات','تحديد النواقص إن وجدت','تجهيز مسار الطلب'], requirements:['صورة الصك','بيانات المالك','أي مخطط أو مستند متاح'], faq:[{q:'هل يمكن تحديث كل الصكوك؟',a:'تُراجع حالة الصك وبيانات العقار أولاً لتحديد المتطلبات والإجراء المناسب.'}], relatedServices:['surveying','land-subdivision-merging'], image:'https://ryan-sa.com/wp-content/uploads/2026/06/Artboard-19-300x210.webp', featured:true, tier:1 },
    { id:'land-subdivision-merging', slug:'land-subdivision-merging', name:'تجزئة ودمج الأراضي', category:'الخدمات العقارية', shortDescription:'إعادة تشكيل حدود العقارات وفق الاحتياج والأنظمة العمرانية.', description:'إجراءات هندسية تهدف إلى إعادة تشكيل حدود العقارات لتلبية الاحتياجات الاستثمارية أو السكنية أو العائلية وفقاً للأنظمة العمرانية.', headline:'خطط عقارك بمرونة أكبر', subheadline:'دراسة هندسية واضحة لتجزئة أو دمج الأراضي قبل اتخاذ القرار.', primaryCTA:'اطلب دراسة تجزئة أو دمج', whatsappMessage:'مرحباً، أرغب في طلب دراسة تجزئة أو دمج أراضٍ.', keywords:['تجزئة الأراضي','دمج الأراضي','تجزئة ودمج العقارات'], seoTitle:'تجزئة ودمج الأراضي | مكتب ريان', metaDescription:'اطلب دراسة تجزئة أو دمج الأراضي من مكتب ريان للمساحة والاستشارات الهندسية.', benefits:['فهم قابلية الإجراء','تصور أوضح للحدود الجديدة','ربط الدراسة بالاحتياج العقاري'], process:['مراجعة بيانات العقار','دراسة المقترح والحدود','توضيح المخرجات والخطوة التالية'], requirements:['صك العقار','مخطط الموقع إن توفر','الهدف من التجزئة أو الدمج'], faq:[{q:'متى تكون تجزئة الأرض مناسبة؟',a:'عندما يكون تقسيم الأرض متوافقاً مع طبيعة العقار والاشتراطات ذات الصلة.'}], relatedServices:['deed-update','unit-sorting'], image:'https://ryan-sa.com/wp-content/uploads/2026/06/Artboard-10-300x210.webp', featured:true, tier:1 },
    { id:'unit-sorting', slug:'unit-sorting', name:'فرز الوحدات العقارية', category:'الخدمات العقارية', shortDescription:'فرز الشقق والمجمعات وتجهيز البيانات اللازمة للوحدات المستقلة.', description:'خدمة تنظيم وفرز الوحدات العقارية بما يساعد على فهم الوحدات ومكوناتها ومتطلبات الإجراء.', headline:'حوّل وحداتك إلى بيانات منظمة', subheadline:'نساعدك على ترتيب المعلومات الهندسية اللازمة لفرز الوحدات العقارية.', primaryCTA:'اطلب فرز الوحدات', whatsappMessage:'مرحباً، أرغب في طلب خدمة فرز الوحدات العقارية.', keywords:['فرز الوحدات العقارية','فرز الشقق','صكوك مستقلة'], seoTitle:'فرز الوحدات العقارية | مكتب ريان', metaDescription:'خدمة فرز الوحدات العقارية وتنظيم بيانات المشروع مع مكتب ريان.', benefits:['تنظيم الوحدات ومكوناتها','توضيح البيانات الهندسية','ربط الفرز بمسار المشروع'], process:['حصر الوحدات والبيانات','مراجعة المخططات والمستندات','تجهيز المخرجات اللازمة'], requirements:['مخططات المشروع','بيانات الوحدات','المستندات العقارية المتاحة'], faq:[{q:'ما المشاريع المناسبة لخدمة الفرز؟',a:'المشاريع التي تحتوي على وحدات عقارية متعددة وتحتاج إلى تنظيم بياناتها وإجراءاتها.'}], relatedServices:['land-subdivision-merging','architectural-design'], image:'https://ryan-sa.com/wp-content/uploads/2026/06/Artboard-11-300x210.webp', featured:true, tier:1 },
    { id:'existing-building', slug:'existing-building', name:'تصحيح مبنى قائم', category:'المباني والتقارير', shortDescription:'حلول هندسية لتصحيح أوضاع الأعيان القائمة واعتمادها.', description:'تقديم الحلول الهندسية المناسبة لمراجعة وضع المبنى القائم وتحديد مسار التصحيح وفق المتاح من بيانات.', headline:'صحّح وضع مبناك بخطوات هندسية', subheadline:'مراجعة واقعية للمبنى ومخرجات تساعدك على معرفة المسار المناسب.', primaryCTA:'اطلب دراسة مبنى قائم', whatsappMessage:'مرحباً، أرغب في طلب دراسة تصحيح مبنى قائم.', keywords:['تصحيح مبنى قائم','تصحيح أوضاع مبنى'], seoTitle:'تصحيح مبنى قائم | مكتب ريان', metaDescription:'حلول هندسية لمراجعة وتصحيح المباني القائمة مع مكتب ريان.', benefits:['تقييم أوضح للوضع الحالي','تحديد البيانات الناقصة','خطة عمل هندسية مبدئية'], process:['جمع بيانات المبنى','المعاينة أو مراجعة المخططات','تحديد المخرجات المناسبة'], requirements:['مخططات المبنى','صور أو بيانات الموقع','أي رخص أو مستندات قائمة'], faq:[{q:'هل تشمل الخدمة كل أنواع المباني؟',a:'يتم تحديد نطاق الخدمة بعد مراجعة نوع المبنى والبيانات المتوفرة.'}], relatedServices:['technical-report','building-permit'], image:'https://ryan-sa.com/wp-content/uploads/2026/06/Artboard-12-300x210.webp', tier:2 },
    { id:'technical-report', slug:'technical-report', name:'تقرير فني', category:'المباني والتقارير', shortDescription:'توثيق وتقييم حالة المباني والمنشآت ومقارنتها بالاشتراطات.', description:'مستند فني يساعد على توثيق حالة المبنى أو المنشأة وتوضيح الملاحظات والمتطلبات ذات الصلة.', headline:'تقرير فني يدعم قرارك', subheadline:'نوثق الحالة ونرتب الملاحظات بشكل يساعدك على اتخاذ الخطوة التالية.', primaryCTA:'اطلب تقريراً فنياً', whatsappMessage:'مرحباً، أرغب في طلب تقرير فني.', keywords:['تقرير فني','تقييم مبنى','فحص مبنى'], seoTitle:'تقرير فني للمباني | مكتب ريان', metaDescription:'اطلب تقريراً فنياً لتوثيق حالة المبنى والمنشأة من مكتب ريان.', benefits:['توثيق الحالة الراهنة','تنظيم الملاحظات','وضوح الاحتياج الهندسي'], process:['فهم هدف التقرير','جمع البيانات والمعاينة','إعداد التقرير وتسليم المخرجات'], requirements:['بيانات المبنى','سبب طلب التقرير','المخططات أو الصور المتوفرة'], faq:[{q:'ما الهدف من التقرير الفني؟',a:'توضيح حالة المبنى والملاحظات الفنية والمعلومات التي تساعد في القرار.'}], relatedServices:['existing-building','engineering-supervision'], image:'https://ryan-sa.com/wp-content/uploads/2026/06/Artboard-13-300x210.webp', tier:2 },
    { id:'license-modification', slug:'license-modification', name:'تعديل وإضافة المكونات', category:'الرخص والاعتمادات', shortDescription:'إضافة أو حذف مكونات البناء في الرخص القائمة عبر منصة بلدي.', description:'خدمة مساعدة في ترتيب بيانات التعديل أو الإضافة المطلوبة على رخصة قائمة وتوضيح الخطوة التالية.', headline:'حدّث رخصتك مع تغيّر مشروعك', subheadline:'تنظيم التعديلات المطلوبة على مكونات البناء بشكل أوضح.', primaryCTA:'اطلب تعديل الرخصة', whatsappMessage:'مرحباً، أرغب في طلب تعديل أو إضافة مكونات في الرخصة.', keywords:['تعديل رخصة بناء','إضافة مكونات','منصة بلدي'], seoTitle:'تعديل وإضافة مكونات الرخصة | مكتب ريان', metaDescription:'تعديل وإضافة مكونات البناء في الرخص القائمة مع مكتب ريان.', benefits:['حصر التعديل المطلوب','فهم المستندات اللازمة','ربط التعديل بمسار الرخصة'], process:['تحديد التغيير','مراجعة الرخصة القائمة','تجهيز البيانات والمتابعة'], requirements:['رقم أو صورة الرخصة','وصف التعديل','المخططات المتاحة'], faq:[{q:'هل يمكن تعديل أي رخصة قائمة؟',a:'يعتمد ذلك على نوع الرخصة وطبيعة التعديل والاشتراطات ذات الصلة.'}], relatedServices:['building-permit','renovation-permit'], image:'https://ryan-sa.com/wp-content/uploads/2026/06/Artboard-14-300x210.webp', tier:2 },
    { id:'quantity-surveying', slug:'quantity-surveying', name:'تمتير وحساب كميات', category:'الإشراف وإدارة المشاريع', shortDescription:'قياس وحساب كميات أعمال البناء والتشطيب لضبط الميزانية والهدر.', description:'قياس وحساب الكميات الهندسية لمواد وأعمال البناء والتشطيب بدقة للمساعدة في ضبط الميزانية وتقليل الهدر.', headline:'أرقام أوضح قبل التنفيذ', subheadline:'نرتب كميات مشروعك لتقليل المفاجآت ودعم قرارك.', primaryCTA:'اطلب حساب الكميات', whatsappMessage:'مرحباً، أرغب في طلب خدمة حساب الكميات.', keywords:['حساب الكميات','تمتير البناء','كميات التشطيب'], seoTitle:'حساب كميات البناء والتشطيب | مكتب ريان', metaDescription:'خدمة تمتير وحساب كميات أعمال البناء والتشطيب مع مكتب ريان.', benefits:['كميات منظمة','دعم ضبط الميزانية','تقليل الهدر والنزاعات'], process:['مراجعة المخططات والنطاق','حصر البنود والكميات','تقديم المخرجات'], requirements:['المخططات','نطاق الأعمال','أي جداول كميات متوفرة'], faq:[{q:'هل يشمل حساب الكميات التشطيبات؟',a:'يمكن أن يشمل أعمال البناء والتشطيب بحسب نطاق المشروع والمخططات المتوفرة.'}], relatedServices:['architectural-design','engineering-supervision'], image:'https://ryan-sa.com/wp-content/uploads/2026/06/Artboard-15-300x210.webp', tier:2 },
    { id:'demolition-permit', slug:'demolition-permit', name:'رخصة هدم', category:'الرخص والاعتمادات', shortDescription:'وثيقة رسمية لإزالة المباني بشكل آمن ومنظم وفق الإجراءات.', description:'مساعدة في تجهيز بيانات مشروع إزالة المبنى وفهم متطلبات مسار رخصة الهدم.', headline:'ابدأ الهدم بإجراء منظم', subheadline:'نرتب لك البيانات اللازمة قبل البدء في إزالة المبنى.', primaryCTA:'ابدأ طلب رخصة هدم', whatsappMessage:'مرحباً، أرغب في بدء طلب رخصة هدم.', keywords:['رخصة هدم','إصدار رخصة هدم'], seoTitle:'إصدار رخصة هدم | مكتب ريان', metaDescription:'ابدأ طلب رخصة هدم مع مكتب ريان للمساحة والاستشارات الهندسية.', benefits:['فهم متطلبات الطلب','تنظيم بيانات المبنى','وضوح الخطوة التالية'], process:['مراجعة المبنى والطلب','تحديد البيانات المطلوبة','تجهيز ومتابعة المسار'], requirements:['بيانات المبنى','المستندات المتاحة','وصف نطاق الهدم'], faq:[{q:'متى أحتاج إلى رخصة هدم؟',a:'عند التخطيط لإزالة مبنى قائم وفق الإجراءات الرسمية ذات الصلة.'}], relatedServices:['technical-report','building-permit'], image:'https://ryan-sa.com/wp-content/uploads/2026/06/Artboard-16-300x210.webp', tier:2 },
    { id:'renovation-permit', slug:'renovation-permit', name:'رخصة ترميم', category:'الرخص والاعتمادات', shortDescription:'تصريح لإصلاح أو تجديد مبنى قائم ضمن نطاق الترميم.', description:'مساعدة في فهم نطاق أعمال الترميم والبيانات اللازمة للمضي في الإجراء المناسب.', headline:'جدّد مبناك بخطوة صحيحة', subheadline:'نوضح لك مسار الترميم قبل بدء الأعمال.', primaryCTA:'ابدأ طلب رخصة ترميم', whatsappMessage:'مرحباً، أرغب في بدء طلب رخصة ترميم.', keywords:['رخصة ترميم','ترميم مبنى','تصريح ترميم'], seoTitle:'إصدار رخصة ترميم | مكتب ريان', metaDescription:'ابدأ طلب رخصة ترميم لمبناك القائم مع مكتب ريان.', benefits:['تحديد نطاق الترميم','تقليل الالتباس في المتطلبات','مسار أكثر وضوحاً'], process:['فهم حالة المبنى','تحديد نطاق الأعمال','تجهيز البيانات والمتابعة'], requirements:['صور المبنى','وصف الأعمال','المستندات المتاحة'], faq:[{q:'هل الترميم يشمل التغيير الإنشائي؟',a:'يُحدد ذلك حسب طبيعة الأعمال، ويجب مراجعة النطاق قبل تقديم الطلب.'}], relatedServices:['license-modification','technical-report'], image:'https://ryan-sa.com/wp-content/uploads/2026/06/Artboard-17-300x210.webp', tier:2 },
    { id:'declaration', slug:'surveying/declaration', name:'إقرار مساحي', category:'الأعمال المساحية', shortDescription:'مستند أو مخطط يوضح مساحة العقار وأبعاده وحدوده.', description:'إعداد البيانات والمخرجات التي توضح مساحة العقار وأبعاده وزواياه وحدوده والأراضي أو الشوارع المجاورة له.', headline:'إقرار مساحي ببيانات واضحة', subheadline:'مخرجات مساحية منظمة تساعد على توثيق واقع العقار.', primaryCTA:'اطلب إقراراً مساحياً', whatsappMessage:'مرحباً، أرغب في طلب إقرار مساحي.', keywords:['إقرار مساحي','مخطط مساحي'], seoTitle:'إقرار مساحي | مكتب ريان', metaDescription:'اطلب إقراراً مساحياً يوضح بيانات عقارك من مكتب ريان.', benefits:['توضيح الأبعاد والحدود','تنظيم بيانات العقار','مساعدة في الإجراءات اللاحقة'], process:['مراجعة بيانات العقار','تنفيذ أو تدقيق القياسات','إعداد المخرج المساحي'], requirements:['بيانات الصك','موقع العقار','المخططات المتاحة'], faq:[{q:'ما الذي يوضحه الإقرار المساحي؟',a:'يوضح مساحة العقار وأبعاده وزواياه وحدوده والبيانات المرتبطة بالموقع.'}], relatedServices:['surveying','deed-update'], image:'https://ryan-sa.com/wp-content/uploads/2026/06/Artboard-18-300x210.webp', tier:2 },
    { id:'architectural-design', slug:'architectural-design', name:'التصميم المعماري', category:'التصميم والاستشارات', shortDescription:'تصميم معماري يوازن بين الرؤية والاحتياج وإمكانات التنفيذ.', description:'تطوير تصور معماري يساعد على تحويل احتياجك إلى مشروع واضح قابل للدراسة والتنفيذ.', headline:'تصميم معماري يبدأ من احتياجك', subheadline:'نحوّل الفكرة إلى تصور واضح يوازن بين الوظيفة والجمال.', primaryCTA:'اطلب عرض تصميم معماري', whatsappMessage:'مرحباً، أرغب في طلب عرض تصميم معماري.', keywords:['تصميم معماري','مكتب تصميم معماري بالرياض'], seoTitle:'تصميم معماري بالرياض | مكتب ريان', metaDescription:'اطلب عرض تصميم معماري يراعي احتياج مشروعك مع مكتب ريان.', benefits:['تصور أوضح للمشروع','ربط التصميم بالواقع','مخرجات تساعد على التنفيذ'], process:['فهم المتطلبات','تطوير التصور','مراجعة واعتماد التوجه'], requirements:['موقع المشروع','الاحتياج والمساحات','أي مراجع أو مخططات'], faq:[{q:'هل يمكن رؤية التصور قبل التنفيذ؟',a:'يتم تحديد مخرجات التصميم المناسبة بحسب نطاق المشروع والاتفاق.'}], relatedServices:['surveying','quantity-surveying'], image:'https://ryan-sa.com/wp-content/uploads/2026/06/Artboard-20-300x210.webp', tier:2 },
    { id:'engineering-supervision', slug:'engineering-supervision', name:'الإشراف الهندسي', category:'الإشراف وإدارة المشاريع', shortDescription:'متابعة تنفيذ المشروع ومراجعة التفاصيل وفق المخططات والنطاق.', description:'إشراف ومتابعة للمشروع تساعد على وضوح مراحل التنفيذ وربطها بالمخططات والتفاصيل.', headline:'إشراف يربط المخطط بالواقع', subheadline:'نرافق مراحل التنفيذ بمتابعة هندسية منظمة.', primaryCTA:'اطلب إشرافاً هندسياً', whatsappMessage:'مرحباً، أرغب في طلب إشراف هندسي.', keywords:['إشراف هندسي','إدارة مشاريع هندسية'], seoTitle:'إشراف هندسي وإدارة مشاريع | مكتب ريان', metaDescription:'اطلب إشرافاً هندسياً ومتابعة لمشروعك مع مكتب ريان.', benefits:['متابعة أوضح للمراحل','رصد الملاحظات','تنسيق أفضل بين المخططات والتنفيذ'], process:['فهم نطاق المشروع','تحديد آلية المتابعة','المراجعة ورفع الملاحظات'], requirements:['مخططات المشروع','نطاق الأعمال','البرنامج أو مراحل التنفيذ'], faq:[{q:'هل الإشراف متاح لكل المشاريع؟',a:'يتم تحديد النطاق المناسب حسب نوع المشروع ومراحله واحتياجات المالك.'}], relatedServices:['quantity-surveying','technical-report'], image:'https://ryan-sa.com/wp-content/uploads/2026/06/Artboard-21-300x210.webp', tier:2 },
  ] as Service[],
  faqs: [{q:'ما الخدمات التي يقدمها مكتب ريان؟',a:'نقدم خدمات المساحة والاستشارات الهندسية والتصميم والإشراف وإصدار الرخص والخدمات العقارية ذات الصلة.'},{q:'هل تقدمون خدمات في الرياض فقط؟',a:'نقدم خدماتنا في الرياض ومختلف مناطق المملكة حسب نوع المشروع.'},{q:'كم تستغرق إجراءات إصدار الرخص؟',a:'تعتمد المدة على نوع المشروع ومتطلبات الجهات المعنية، ويتم توضيح الجدول الزمني قبل البدء.'},{q:'هل يمكن الحصول على استشارة قبل بدء المشروع؟',a:'نعم، يمكنك طلب استشارة أولية لمناقشة احتياجاتك والخطوة المناسبة.'}],
  equipment: [{name:'جهاز GPS المساحي',label:'دقة عالية',image:asset('equip-gps_af96951a.png')},{name:'جهاز Total Station',label:'احترافي',image:asset('equip-total-station_dbda3235.png')},{name:'طائرة درون مساحية',label:'تقنية حديثة',image:asset('equip-drone_13cc0e70.png')},{name:'جهاز Level الآلي',label:'دقة مليمترية',image:asset('equip-level_3043410d.png')},{name:'جهاز Laser Scanner',label:'احترافي',image:asset('equip-laser_612f2ba2.png')},{name:'رادار GPR',label:'تقنية حديثة',image:asset('equip-gpr_a1707e3e.png')}],
  values: [{id:'expertise',title:'الخبرة',description:'نعتمد على خبرات هندسية متخصصة لضمان أفضل الحلول.'},{id:'quality',title:'الجودة',description:'نلتزم بأعلى معايير الجودة في جميع مراحل العمل.'},{id:'transparency',title:'الشفافية',description:'نوفر وضوحاً كاملاً في الإجراءات والتكاليف والنتائج.'},{id:'commitment',title:'الالتزام',description:'ننجز المشاريع وفق الجداول الزمنية المتفق عليها.'}],
  aboutImage: asset('team-office_54c5e9e9.jpg'),
  trustImage: asset('team-field_3e354906.jpg'),
  clientLogos: [asset('client-1_local.jpg'),asset('client-2_local.jpg'),asset('client-3_local.jpg'),asset('client-4_local.jpg'),asset('client-5_local.jpg'),asset('client-6_local.jpg'),asset('client-7_local.jpg'),asset('client-8_local.jpg'),asset('client-9_local.jpg'),asset('client-10_local.jpg'),asset('client-11_local.jpg'),asset('client-12_local.jpg'),asset('client-13_local.jpg'),asset('client-14_local.jpg'),asset('client-15_local.jpg'),asset('client-16_local.jpg'),asset('client-17_local.jpg'),asset('client-18_local.jpg'),asset('client-19_local.jpg'),asset('client-20_local.jpg'),asset('client-21_local.jpg'),asset('client-22_local.jpg'),asset('client-23_local.jpg'),asset('client-24_local.jpg')],
  tracking: { ga4MeasurementId: import.meta.env.VITE_GA4_MEASUREMENT_ID || '', gtmContainerId: import.meta.env.VITE_GTM_CONTAINER_ID || '', googleAdsId: import.meta.env.VITE_GOOGLE_ADS_ID || '', googleAdsConversionLabel: import.meta.env.VITE_GOOGLE_ADS_CONVERSION_LABEL || '' }
};

export const findService = (slug: string) => siteData.services.find(s => s.slug === slug || s.id === slug);
export const whatsappLink = (message?: string) => `${siteData.contact.whatsapp}?text=${encodeURIComponent(message || 'مرحباً، أرغب في معرفة المزيد عن خدمات مكتب ريان.')}`;
export const track = (event: string, params: Record<string, unknown> = {}) => { window.dataLayer = window.dataLayer || []; window.dataLayer.push({ event, ...params }); const gtag = (window as any).gtag; if (gtag) gtag('event', event, params); };
declare global { interface Window { dataLayer: Record<string, unknown>[]; } }
